"""add ai_summary and ai_summary_updated_at to conversations

Revision ID: 113b1d5ef203
Revises: 9eea59675ee4
Create Date: 2025-10-09 17:00:48.216842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '113b1d5ef203'
down_revision: Union[str, Sequence[str], None] = '9eea59675ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('conversations', sa.Column('ai_summary_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'ai_summary_updated_at')
    op.drop_column('conversations', 'ai_summary')
    # ### end Alembic commands ###
